name: Gitleaks Secret Scan

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    name: Scan for secrets with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git --verbose --exit-code 1
          # Remove --no-git to scan full commit history
