name: Gitleaks Secret Scan

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  gitleaks:
    name: Scan for secrets with Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          scan-dir: '.' # Scan directory (all files)
          config-path: '' # Empty means use defualt roles
          redact: false # Hide secrets from logs
          verbose: true 
          fail: true # Fail if any secrets are found
